# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka
# 基础配置
server:
  port: 8081
  servlet:
    context-path: /client-provider
# 应用配置
spring:
  application:
    name: client-provider
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:44444