# 基础配置
server:
  port: 8081
  servlet:
    context-path: /client-provider
# 应用配置
spring:
  application:
    name: client-provider
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:44444
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka