# 基础配置
server:
  port: 11111
# 服务配置
spring:
  application:
    name: server-eureka
# 注册中心
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false