server:
  port: 8081
  servlet:
    context-path: /boot

spring:
  application:
    name: demo-service-boot

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/demo
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml