# 基础配置
server:
  port: 22222
  servlet:
    context-path: /server-config
# 服务配置
spring:
  application:
    name: server-config
  # 配置中心
  cloud:
    config:
      server:
        git:
          uri: https://github.com/20gongzi/demo-project-config.git
          default-label: main
          search-paths: /**
  # 消息总线
  rabbitmq:
    host: 192.168.11.128
    username: guest
    password: guest
    virtual-host: /
# 注册中心
eureka:
  instance:
    metadata-map:
      configPath: ${server.servlet.context-path}
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka
# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: