# 基础配置
server:
  port: 55555
# 服务配置
spring:
  application:
    name: server-admin
# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka
# 监控配置
management:
  endpoints:
    web: # HTTP端点配置
      exposure:
        include: "*"
        exclude: