# 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka
# 基础配置
server:
  port: 44444
# 服务配置
spring:
  application:
    name: server-zipkin

management:
  metrics:
    web:
      server:
        # 取消自动定时，如果不设置为false，时间序列数量可能会增长过大，导致异常
        auto-time-requests: false