server:
  port: 8082
  servlet:
    context-path: /client-consumer

spring:
  application:
    name: client-consumer

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka